name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        EXAMPLE_ENVIROMENT_VARIABLE:  ${{ secrets.EXAMPLE_ENVIROMENT_VARIABLE }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source

    - name: Push to Custom Feed
      shell: bash
      run: |
        PACKAGE_FILE=$(find Frends.Community.FixedWidthFlatFile\bin\Release -name "*.nupkg" ! -name "*.symbols.nupkg" | head -n 1)
        
        curl -X POST "https://frends-fsp-cloudprod-agent.frendsapp.com/api/community-tasks/v1/push?feed_type=test" \
          -H "x-api-key: ${{ secrets.FRENDS_COMMUNITY_TASKS_API_KEY }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"$PACKAGE_FILE"
